//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebApp.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.Resources = new HashSet<Resource>();
            this.Audiences = new HashSet<Audience>();
            this.Speakers = new HashSet<Speaker>();
            this.Tags = new HashSet<Tag>();
            this.Tracks = new HashSet<Track>();
        }
    
        public int ID { get; set; }
        public int ConferenceID { get; set; }
        public string UKey { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> TimeSlotID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public bool IsSponsorSession { get; set; }
        public bool RequiresRegistration { get; set; }
        public Nullable<System.DateTime> RegistrationStartDate { get; set; }
        public string Code { get; set; }
        public Nullable<int> SessionTypeID { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual Conference Conference { get; set; }
        public virtual Level Level { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<Resource> Resources { get; set; }
        public virtual SessionType SessionType { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
        public virtual ICollection<Audience> Audiences { get; set; }
        public virtual ICollection<Speaker> Speakers { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<Track> Tracks { get; set; }
    }
}
